######################################################################
# Hexapod Parameters
######################################################################

hexapod_type: flexipod

time_delta: 0.02

#Compensation
imu_compensation: true
auto_compensation: false
manual_compensation: true

gait_type: tripod_gait

######################################################################

root_offset_AL: [0.07, 0.12, 0.0] #Front Left Leg
root_offset_AR: [0.07, 0.12, 0.0] #Front Right Leg
root_offset_BL: [0.11, 0.0, 0.0] #Middle Left Leg
root_offset_BR: [0.11, 0.0, 0.0] #Middle Right Leg
root_offset_CL: [0.07, -0.12, 0.0] #Back Left Leg
root_offset_CR: [0.07, -0.12, 0.0] #Back Right Leg

hip_offset_AL: [0.066, 0.0, 0.0] #Front Left Leg
hip_offset_AR: [0.066, 0.0, 0.0] #Front Right Leg
hip_offset_BL: [0.066, 0.0, 0.0] #Middle Left Leg
hip_offset_BR: [0.066, 0.0, 0.0] #Middle Right Leg
hip_offset_CL: [0.066, 0.0, 0.0] #Back Left Leg
hip_offset_CR: [0.066, 0.0, 0.0] #Back Right Leg

knee_offset_AL: [0.11, 0.0, 0.0] #Front Left Leg
knee_offset_AR: [0.11, 0.0, 0.0] #Front Right Leg
knee_offset_BL: [0.11, 0.0, 0.0] #Middle Left Leg
knee_offset_BR: [0.11, 0.0, 0.0] #Middle Right Leg
knee_offset_CL: [0.11, 0.0, 0.0] #Back Left Leg
knee_offset_CR: [0.11, 0.0, 0.0] #Back Right Leg

tip_offset_AL: [1.0, 0.0, 0.0] #Front Left Leg
tip_offset_AR: [1.0, 0.0, 0.0] #Front Right Leg
tip_offset_BL: [1.0, 0.0, 0.0] #Middle Left Leg
tip_offset_BR: [1.0, 0.0, 0.0] #Middle Right Leg
tip_offset_CL: [1.0, 0.0, 0.0] #Back Left Leg
tip_offset_CR: [1.0, 0.0, 0.0] #Back Right Leg

stance_leg_yaws: [0.77, 0, -0.77]
yaw_limits: [1.4, 1.4, 1.4]
knee_limits: [0, 2.0]
hip_limits: [-3.0, 3.0] #CHECK THIS VALUE

joint_max_angular_speeds: [10000,10000,10000] #CHECK THIS VALUE

dynamixel_interface: true

######################################################################
# Walk Controller Parameters
######################################################################

step_frequency: 0.2
step_clearance: 0.04
body_clearance: 0.86
leg_span_scale: 0.8

max_acceleration: 0.1
max_curvature_speed: 0.4

step_curvature_allowance: 0.7

interface_setup_speed: 2.0

######################################################################
# Pose Controller Parameters
######################################################################

#Move to Start
move_to_start: true
move_legs_sequentially: false
time_to_start: 5.0

#Auto pose compensation
pitch_amplitude: 0.025
roll_amplitude: 0.025

#Manual pose compensation  
max_pose_time: 2.0
max_roll: 0.075
max_pitch: -0.075
max_yaw: 0.2
max: 0.05
max_y: 0.05
max_z: 0.05

######################################################################
######################################################################
