######################################################################
# Gait Parameters
######################################################################

#Note: Make sure stance/swing phase are even

hexapod:
  gait_parameters:
  
######################################################################
    
    wave_gait:
    
      stance_phase: 10 #16
      swing_phase: 2 #2
      phase_offset: 2 #3

      offset_multiplier: [2,5,3,0,4,1]

######################################################################

    tripod_gait:
    
      stance_phase: 2
      swing_phase: 2
      phase_offset: 2

      offset_multiplier: [0,1,1,0,0,1]

######################################################################

    ripple_gait:
    
      stance_phase: 4
      swing_phase: 2
      phase_offset: 1  

      offset_multiplier: [2,5,4,1,0,3]
  
######################################################################

    amble_gait:
      
      stance_phase: 2 #7
      swing_phase: 1 #1
      phase_offset: 1 #3
      
      offset_multiplier: [1,0,2,2,0,1]
      
######################################################################
######################################################################