######################################################################
# Gait Parameters
######################################################################

hexapod:
  gait_parameters:
  
######################################################################
    
    wave_gait:
    
      stance_phase: 78
      swing_phase: 8
      transition_period: 2
      phase_offset: 15

      offset_multiplier: [2,5,3,0,4,1]

######################################################################

    tripod_gait:
    
      stance_phase: 4
      swing_phase: 4
      transition_period: 1
      phase_offset: 5  

      offset_multiplier: [0,1,1,0,0,1]

######################################################################

    ripple_gait:
    
      stance_phase: 18
      swing_phase: 8
      transition_period: 2
      phase_offset: 5  

      offset_multiplier: [2,5,4,1,0,3]
  
######################################################################

    experimental_gait:
      
      stance_phase: 33
      swing_phase: 8
      transition_period: 2
      phase_offset: 15
      
      offset_multiplier: [1,0,2,2,0,1]
      
######################################################################
