######################################################################
# Hexapod Parameters
######################################################################

hexapod_type: lobsang
move_to_start: true
move_legs_sequentially: false
time_to_start: 5.0

imu_compensation: false
auto_compensation: false
pitch_amplitude: 0.025
roll_amplitude: 0.025
manual_compensation: true

gait_type: tripod_gait

######################################################################

stance_leg_yaws: [0.77, 0, -0.77]
yaw_limits: [1.4, 1.4, 1.4]
knee_limits: [0, 1.9]
hip_limits: [-3.0,3.0] #CHECK THIS VALUE

joint_max_angular_speeds: [10000,10000,10000] #CHECK THIS VALUE

dynamixel_interface: true

######################################################################
# Walk Controller Parameters
######################################################################

step_frequency: 1.0
step_clearance: 0.1
body_clearance: -1.0
leg_span_scale: 1.0

max_acceleration: 0.1
max_curvature_speed: 0.4

step_curvature_allowance: 0.7

interface_setup_speed: 2.5

######################################################################
######################################################################
